
CREATE VIEW [StockListSAP_V100].[DiscountedProduct]
AS
          SELECT CONVERT(INT, 1) AS ProductId, CONVERT(FLOAT, 2.99) AS DiscountPrice, DATEADD(DAY,1,CONVERT(DATE,GETDATE())) AS PriceValidUntil
UNION ALL SELECT CONVERT(INT, 2) AS ProductId, CONVERT(FLOAT, 1.99) AS DiscountPrice, DATEADD(DAY,3,CONVERT(DATE,GETDATE())) AS PriceValidUntil
UNION ALL SELECT CONVERT(INT, 3) AS ProductId, CONVERT(FLOAT, 1.99) AS DiscountPrice, DATEADD(DAY,1,CONVERT(DATE,GETDATE())) AS PriceValidUntil